export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_ERROR = "LOGOUT_USER_ERROR";

export const GET_PRODUCT_LISTS = "GET_PRODUCT_LISTS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";

export const GET_CART_LIST_PRODUCT = "GET_CART_LIST_PRODUCT";
export const REMOVE_CART_LIST_PRODUCT = "REMOVE_CART_LIST_PRODUCT";
export const REMOVE_ALL_CART_LIST_PRODUCT = "REMOVE_ALL_CART_LIST_PRODUCT";
export const INC_CART_LIST_PRODUCT = "INC_CART_LIST_PRODUCT";
export const DEC_CART_LIST_PRODUCT = "DEC_CART_LIST_PRODUCT";
export const TOTAL_CART_LIST_PRICE = "TOTAL_CART_LIST_PRICE";
